name: build-bigpod

on:
  schedule:
    - cron: '15 00 * * *'
  push:
    branches:
      - main
  workflow_dispatch:
      
jobs: 
  setup:
    runs-on: ubuntu-22.04
    outputs:
      date: ${{ steps.exec-datetime.outputs.DATE }}
    steps:
    - id: exec-datetime
      name: exec datetime
      shell: bash
      run: echo "DATE=$(date +"%d%m%y%H%M")" >> $GITHUB_OUTPUT

  build-base:
    runs-on: ubuntu-22.04
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        basetype: [fedora, ubuntu]
        arch: [arm64, amd64]
        exclude:
        - basetype: fedora
          arch: arm64
    steps:
    - name: Checkout Push to Registry action
      uses: actions/checkout@v3
    - name: install-multiarch
      uses: docker/setup-qemu-action@v1
    - name: build
      shell: bash
      working-directory: ./${{matrix.basetype}}/baseenv
      env:
        DATE: ${{ needs.setup.outputs.date }}
      run: podman build . --platform=linux/${{matrix.arch}} -t ghcr.io/bigpod98/bigpodsb/distroboxes/${{matrix.basetype}}/baseenv:$DATE-${{matrix.arch}}
    - name: login
      shell: bash
      run: podman login ghcr.io -u bigpod98 -p ${{ secrets.GITHUB_TOKEN }}
    - name: push
      shell: bash
      env:
        DATE: ${{ needs.setup.outputs.date }}
      run: podman push ghcr.io/bigpod98/bigpodsb/distroboxes/${{matrix.basetype}}/baseenv:$DATE-${{matrix.arch}}

  build-manifests-1:
    runs-on: ubuntu-22.04
    needs: 
      - build-base
      - setup
    strategy:
      fail-fast: false
      matrix:
        basetype: [fedora, ubuntu]
        exclude:
          - basetype: fedora
    steps:
    - name: login
      shell: bash
      run: podman login ghcr.io -u bigpod98 -p ${{ secrets.GITHUB_TOKEN }}
    - name: create manifest
      shell: bash
      run: podman manifest create ${{matrix.basetype}}-manifest
    - name: add arm64
      shell: bash
      env:
        DATE: ${{ needs.setup.outputs.date }}
      run: podman manifest add ${{matrix.basetype}}-manifest ghcr.io/bigpod98/bigpodsb/distroboxes/${{matrix.basetype}}/baseenv:$DATE-arm64
    - name: add amd64
      shell: bash
      env:
        DATE: ${{ needs.setup.outputs.date }}
      run: podman manifest add ${{matrix.basetype}}-manifest ghcr.io/bigpod98/bigpodsb/distroboxes/${{matrix.basetype}}/baseenv:$DATE-amd64
    - name: push manifest
      run: podman manifest push ${{matrix.basetype}}-manifest ghcr.io/bigpod98/bigpodsb/distroboxes/${{matrix.basetype}}/baseenv:latest
      
  build-manifests-2:
    runs-on: ubuntu-22.04
    needs: 
      - build-base
      - setup
    strategy:
      fail-fast: false
      matrix:
        basetype: [fedora, ubuntu]
        exclude:
          - basetype: ubuntu
    steps:
    - name: login
      shell: bash
      run: podman login ghcr.io -u bigpod98 -p ${{ secrets.GITHUB_TOKEN }}
    - name: create manifest
      shell: bash
      run: podman manifest create ${{matrix.basetype}}-manifest
    - name: add amd64
      shell: bash
      env:
        DATE: ${{ needs.setup.outputs.date }}
      run: podman manifest add ${{matrix.basetype}}-manifest ghcr.io/bigpod98/bigpodsb/distroboxes/${{matrix.basetype}}/baseenv:$DATE-amd64
    - name: push manifest
      run: podman manifest push ${{matrix.basetype}}-manifest ghcr.io/bigpod98/bigpodsb/distroboxes/${{matrix.basetype}}/baseenv:latest

  build-envs:
    runs-on: ubuntu-22.04
    needs: 
      - setup
      - build-manifests-1
      - build-manifests-2
    strategy:
      fail-fast: false
      matrix:
        basetype: [fedora, ubuntu]
        distroboxtype: [desktopenv, standardenv, systemsenv]
        arch: [arm64, amd64]
        exclude:
          - basetype: fedora
            arch: arm64
          - basetype: fedora
            distroboxtype: desktopenv
          - basetype: fedora
            distroboxtype: standardenv
          - basetype: fedora
            distroboxtype: systemsenv     
    steps:
    - name: install-multiarch
      uses: docker/setup-qemu-action@v1
    - name: Checkout Push to Registry action
      uses: actions/checkout@v3
    - name: build
      shell: bash
      env:
        DATE: ${{ needs.setup.outputs.date }}
      working-directory: ./${{matrix.basetype}}/${{matrix.distroboxtype}}
      run: podman build . --platform=linux/${{matrix.arch}} -t ghcr.io/bigpod98/bigpodsb/distroboxes/${{matrix.basetype}}/${{matrix.distroboxtype}}:$DATE-${{matrix.arch}}
    - name: login
      shell: bash
      run: podman login ghcr.io -u bigpod98 -p ${{ secrets.GITHUB_TOKEN }}
    - name: push
      env:
        DATE: ${{ needs.setup.outputs.date }}
      shell: bash
      run: podman push ghcr.io/bigpod98/bigpodsb/distroboxes/${{matrix.basetype}}/${{matrix.distroboxtype}}:$DATE-${{matrix.arch}}

  build-envs-manifests-1:
    runs-on: ubuntu-22.04
    needs: 
      - build-envs
      - setup
    strategy:
      fail-fast: false
      matrix:
        basetype: [fedora, ubuntu]
        distroboxtype: [desktopenv, standardenv, systemsenv]
        exclude:
          - basetype: fedora
    steps:
    - name: login
      shell: bash
      run: podman login ghcr.io -u bigpod98 -p ${{ secrets.GITHUB_TOKEN }}
    - name: create manifest
      shell: bash
      run: podman manifest create ${{matrix.basetype}}-manifest
    - name: add arm64
      shell: bash
      env:
        DATE: ${{ needs.setup.outputs.date }}
      run: podman manifest add ${{matrix.basetype}}-manifest ghcr.io/bigpod98/bigpodsb/distroboxes/${{matrix.basetype}}/${{matrix.distroboxtype}}:$DATE-arm64
    - name: add amd64
      shell: bash
      env:
        DATE: ${{ needs.setup.outputs.date }}
      run: podman manifest add ${{matrix.basetype}}-manifest ghcr.io/bigpod98/bigpodsb/distroboxes/${{matrix.basetype}}/${{matrix.distroboxtype}}:$DATE-amd64
    - name: push manifest
      run: podman manifest push ${{matrix.basetype}}-manifest ghcr.io/bigpod98/bigpodsb/distroboxes/${{matrix.basetype}}/${{matrix.distroboxtype}}:latest

#  build-fedorabased:
#    runs-on: ubuntu-22.04
#    needs: build-fedora-base
#    strategy:
#      fail-fast: false
#      matrix:
#        distroboxtype: [virtenv]
#    steps:
#    - name: Checkout Push to Registry action
#      uses: actions/checkout@v3
#    - name: build
#      shell: bash
#      working-directory: ./fedora/${{matrix.distroboxtype}}
#      run: podman build . -t ghcr.io/bigpod98/bigpodsb/distroboxes/fedorabased/${{matrix.distroboxtype}}:latest
#    - name: login
#      shell: bash
#      run: podman login ghcr.io -u bigpod98 -p ${{ secrets.GITHUB_TOKEN }}
#    - name: push
#      shell: bash
#      run: podman push ghcr.io/bigpod98/bigpodsb/distroboxes/fedorabased/${{matrix.distroboxtype}}:latest
