name: build-bigpod

on:
  schedule:
    - cron: '15 00 * * *'
  push:
    branches:
      - main
  workflow_dispatch:
      
jobs: 
#  build-ub-base:
#    runs-on: ubuntu-22.04
#    steps:
#    - name: Checkout Push to Registry action
#      uses: actions/checkout@v3
#    - name: install-multiarch
#      uses: docker/setup-qemu-action@v1
#    - name: build amd64
#      shell: bash
#      working-directory: ./ubuntu/baseenv
#      run: podman build . --manifest ubbased-baseenv-manifest --platform=linux/amd64
#    - name: build arm64
#      shell: bash
#      working-directory: ./ubuntu/baseenv
#      run: podman build . --manifest ubbased-baseenv-manifest --platform=linux/arm64
#    - name: login
#      shell: bash
#      run: podman login ghcr.io -u bigpod98 -p ${{ secrets.GITHUB_TOKEN }}
#    - name: push
#      shell: bash
#      run: podman manifest push --all ubbased-baseenv-manifest ghcr.io/bigpod98/bigpodsb/distroboxes/ubbased/baseenv:latest
#  build-fedora-base:
#    runs-on: ubuntu-22.04
#    steps:
#    - name: Checkout Push to Registry action
#      uses: actions/checkout@v3
#    - name: build
#      shell: bash
#      working-directory: ./fedora/baseenv
#      run: podman build . -t ghcr.io/bigpod98/bigpodsb/distroboxes/fedorabased/baseenv:latest
#    - name: login
#      shell: bash
#      run: podman login ghcr.io -u bigpod98 -p ${{ secrets.GITHUB_TOKEN }}
#    - name: push
#      shell: bash
#      run: podman push ghcr.io/bigpod98/bigpodsb/distroboxes/fedorabased/baseenv:latest

  build-base:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        basetype: [fedora, ubuntu]
        arch: [arm64, amd64]
    steps:
    - name: Checkout Push to Registry action
      uses: actions/checkout@v3
    - name: build
      shell: bash
      working-directory: ./${{matrix.basetype}}/baseenv
      run: podman build . --platform=linux/${{matrix.arch}} -t ghcr.io/bigpod98/bigpodsb/distroboxes/${{matrix.basetype}}/baseenv:
    - name: login
      shell: bash
      run: podman login ghcr.io -u bigpod98 -p ${{ secrets.GITHUB_TOKEN }}
    - name: push
      shell: bash
      run: podman push ghcr.io/bigpod98/bigpodsb/distroboxes/ubbased/${{matrix.distroboxtype}}:latest

  build-ubbased:
    runs-on: ubuntu-22.04
    needs: build-base
    strategy:
      fail-fast: false
      matrix:
        distroboxtype: [desktopenv, standardenv, systemsenv]
    steps:
    - name: Checkout Push to Registry action
      uses: actions/checkout@v3
    - name: build
      shell: bash
      working-directory: ./ubuntu/${{matrix.distroboxtype}}
      run: podman build . --all-platforms -t ghcr.io/bigpod98/bigpodsb/distroboxes/ubbased/${{matrix.distroboxtype}}:latest
    - name: login
      shell: bash
      run: podman login ghcr.io -u bigpod98 -p ${{ secrets.GITHUB_TOKEN }}
    - name: push
      shell: bash
      run: podman push ghcr.io/bigpod98/bigpodsb/distroboxes/ubbased/${{matrix.distroboxtype}}:latest

  
  
#  build-fedorabased:
#    runs-on: ubuntu-22.04
#    needs: build-fedora-base
#    strategy:
#      fail-fast: false
#      matrix:
#        distroboxtype: [virtenv]
#    steps:
#    - name: Checkout Push to Registry action
#      uses: actions/checkout@v3
#    - name: build
#      shell: bash
#      working-directory: ./fedora/${{matrix.distroboxtype}}
#      run: podman build . -t ghcr.io/bigpod98/bigpodsb/distroboxes/fedorabased/${{matrix.distroboxtype}}:latest
#    - name: login
#      shell: bash
#      run: podman login ghcr.io -u bigpod98 -p ${{ secrets.GITHUB_TOKEN }}
#    - name: push
#      shell: bash
#      run: podman push ghcr.io/bigpod98/bigpodsb/distroboxes/fedorabased/${{matrix.distroboxtype}}:latest
