name: build-bigpod

on:
  schedule:
    - cron: '15 00 * * *'
  push:
    branches:
      - main
  workflow_dispatch:
      
jobs: 
#  build-ub-base:
#    runs-on: ubuntu-22.04
#    steps:
#    - name: Checkout Push to Registry action
#      uses: actions/checkout@v3
#    - name: install-multiarch
#      uses: docker/setup-qemu-action@v1
#    - name: build amd64
#      shell: bash
#      working-directory: ./ubuntu/baseenv
#      run: podman build . --manifest ubbased-baseenv-manifest --platform=linux/amd64
#    - name: build arm64
#      shell: bash
#      working-directory: ./ubuntu/baseenv
#      run: podman build . --manifest ubbased-baseenv-manifest --platform=linux/arm64
#    - name: login
#      shell: bash
#      run: podman login ghcr.io -u bigpod98 -p ${{ secrets.GITHUB_TOKEN }}
#    - name: push
#      shell: bash
#      run: podman manifest push --all ubbased-baseenv-manifest ghcr.io/bigpod98/bigpodsb/distroboxes/ubbased/baseenv:latest
#  build-fedora-base:
#    runs-on: ubuntu-22.04
#    steps:
#    - name: Checkout Push to Registry action
#      uses: actions/checkout@v3
#    - name: build
#      shell: bash
#      working-directory: ./fedora/baseenv
#      run: podman build . -t ghcr.io/bigpod98/bigpodsb/distroboxes/fedorabased/baseenv:latest
#    - name: login
#      shell: bash
#      run: podman login ghcr.io -u bigpod98 -p ${{ secrets.GITHUB_TOKEN }}
#    - name: push
#      shell: bash
#      run: podman push ghcr.io/bigpod98/bigpodsb/distroboxes/fedorabased/baseenv:latest

  setup:
    runs-on: ubuntu-22.04
    outputs:
      date: ${{ steps.exec-datetime.outputs.DATE }}
    steps:
    - id: exec-datetime
      name: exec datetime
      shell: bash
      run: echo "DATE=$(date +"%d%m%y%H%M")" >> $GITHUB_OUTPUT

  build-base:
    runs-on: ubuntu-22.04
    needs: setup
    strategy:
      fail-fast: false
      matrix:
        basetype: [fedora, ubuntu]
        arch: [arm64, amd64]
    steps:
    - name: Checkout Push to Registry action
      uses: actions/checkout@v3
    - name: install-multiarch
      uses: docker/setup-qemu-action@v1
    - name: build
      shell: bash
      working-directory: ./${{matrix.basetype}}/baseenv
      env:
        DATE: ${{ needs.setup.outputs.date }}
      run: podman build . --platform=linux/${{matrix.arch}} -t ghcr.io/bigpod98/bigpodsb/distroboxes/${{matrix.basetype}}/baseenv:$DATE-${{matrix.arch}}
    - name: login
      shell: bash
      run: podman login ghcr.io -u bigpod98 -p ${{ secrets.GITHUB_TOKEN }}
    - name: push
      shell: bash
      env:
        DATE: ${{ needs.setup.outputs.date }}
      run: podman push ghcr.io/bigpod98/bigpodsb/distroboxes/${{matrix.basetype}}/baseenv:$DATE-${{matrix.arch}}

  build-manifests:
    runs-on: ubuntu-22.04
    needs: build-base
    strategy:
      fail-fast: false
      matrix:
        basetype: [fedora, ubuntu]
    steps:
    - name: pull arm64 image
      shell: bash
      run: podman pull ghcr.io/bigpod98/bigpodsb/distroboxes/${{matrix.basetype}}/baseenv:${{ needs.setup.outputs.date }}-arm64
    - name: pull amd64 image
      shell: bash
      run: podman pull ghcr.io/bigpod98/bigpodsb/distroboxes/${{matrix.basetype}}/baseenv:${{ needs.setup.outputs.date }}-amd64
    - name: create manifest
      shell: bash
      run: podman manifest create ${{matrix.basetype}}-manifest
    - name: add arm64
      shell: bash
      run: podman manifest add ${{matrix.basetype}}-manifest ghcr.io/bigpod98/bigpodsb/distroboxes/${{matrix.basetype}}/baseenv:${{ needs.setup.outputs.date }}-arm64
    - name: add amd64
      shell: bash
      run: podman manifest add ${{matrix.basetype}}-manifest ghcr.io/bigpod98/bigpodsb/distroboxes/${{matrix.basetype}}/baseenv:${{ needs.setup.outputs.date }}-amd64
    - name: push manifest
      run: podman manifest push ${{matrix.basetype}}-manifest ghcr.io/bigpod98/bigpodsb/distroboxes/${{matrix.basetype}}/baseenv:latest

  build-ubbased:
    runs-on: ubuntu-22.04
    needs: build-manifests
    strategy:
      fail-fast: false
      matrix:
        distroboxtype: [desktopenv, standardenv, systemsenv]
    steps:
    - name: Checkout Push to Registry action
      uses: actions/checkout@v3
    - name: build
      shell: bash
      working-directory: ./ubuntu/${{matrix.distroboxtype}}
      run: podman build . --all-platforms -t ghcr.io/bigpod98/bigpodsb/distroboxes/ubbased/${{matrix.distroboxtype}}:latest
    - name: login
      shell: bash
      run: podman login ghcr.io -u bigpod98 -p ${{ secrets.GITHUB_TOKEN }}
    - name: push
      shell: bash
      run: podman push ghcr.io/bigpod98/bigpodsb/distroboxes/ubbased/${{matrix.distroboxtype}}:latest

#  build-fedorabased:
#    runs-on: ubuntu-22.04
#    needs: build-fedora-base
#    strategy:
#      fail-fast: false
#      matrix:
#        distroboxtype: [virtenv]
#    steps:
#    - name: Checkout Push to Registry action
#      uses: actions/checkout@v3
#    - name: build
#      shell: bash
#      working-directory: ./fedora/${{matrix.distroboxtype}}
#      run: podman build . -t ghcr.io/bigpod98/bigpodsb/distroboxes/fedorabased/${{matrix.distroboxtype}}:latest
#    - name: login
#      shell: bash
#      run: podman login ghcr.io -u bigpod98 -p ${{ secrets.GITHUB_TOKEN }}
#    - name: push
#      shell: bash
#      run: podman push ghcr.io/bigpod98/bigpodsb/distroboxes/fedorabased/${{matrix.distroboxtype}}:latest
